stages:
  setup:
    cmd: src/setup.sh
  clean:
    cmd: >
      src/clean_expression.py
      data/zhong2021/s4-plasma_protein_profiling.csv
      data/zhong2021/expression.csv
      --meta_out data/zhong2021/meta.csv
      --rename_group_id
    deps:
      - src/clean_expression.py
      - data/zhong2021/s4-plasma_protein_profiling.csv
    outs:
      - data/zhong2021/expression.csv
      - data/zhong2021/meta.csv
  bin_expression:
    cmd: >
      src/motif_mining/graphs/bin_expression.py 
      data/zhong2021/expression.csv 
      data/mining 
      --value npx 
      --var_id symbol
      --idmap data/string/string_v12_idmap.csv
    deps:
      - src/motif_mining/graphs/bin_expression.py
      - data/zhong2021/expression.csv
    outs: 
      - data/mining/expression/expression_binned.csv
  generate_graphs:
    cmd: >
      src/motif_mining/graphs/generate.py 
      data/mining/expression/expression_binned.csv 
      data/string/9606.protein.physical.links.detailed.v12.0.txt.gz
      data/mining/graphs 
      --clobber
    deps:
      - src/motif_mining/graphs/generate.py
      - data/mining/expression/expression_binned.csv
      - data/string/string_v12_idmap.csv

  ## Split data exp
  setup_exp:
    cmd: >
      src/motif_mining/mining/setup_experiment.py
      data/zhong2021/meta.csv
      data/mining/graphs
      data/mining/240522-split
      --p_train 0.8
      --symlink
      --meta_out data/mining/240522-split/meta.csv
      --override_train_mask data/og_sample_ids.txt
  
  # mine/extract on training set only
  mine:
    cmd: >
      src/motif_mining/mining/gaston_cov.py
      data/mining/240522-split/train
      --size 3
      --support 30
    deps:
      - data/mining/240522-split/train/graphs
    outs:
      - data/mining/240522-split/train/gaston_files

  join_metadata:
    cmd: >
      src/motif_mining/mining/join_metadata.py
      data/zhong2021/meta.csv
      data/mining/240522-split/train/gaston_files
      data/mining/240522-split/train/meta.csv
    outs:
      - data/mining/240522-split/train/meta.csv
  extract:
    cmd: >
      src/motif_mining/mining/extract_results.py
      data/mining/240522-split/train
      --purge_motifs
      --processes 8
    outs:
      - data/mining/240522-split/train/motifs
  match:
    cmd: >
      src/motif_mining/mining/match_motifs.py
      data/mining/240522-split/train/motifs
      data/mining/expression/expression_binned.csv
      data/mining/240522-split/train/meta.csv
      data/mining/240522-split/meta.csv
      data/mining/240522-split/freq/matched_motifs.csv
    outs:
      - data/mining/240522-split/freq/matched_motifs.csv
  filter:
    cmd: >
      src/motif_mining/mining/filter.py
      data/mining/240522-split/freq/matched_motifs.csv
      data/string/9606.protein.physical.links.detailed.v12.0.txt.gz
      data/mining/240522-split/freq/matched_motifs.csv
      --no_cache
  freq:
    cmd: >
      src/motif_mining/freq/freq.py
      data/mining/240522-split/freq/matched_motifs.csv
    deps:
      - data/mining/240522-split/freq/matched_motifs.csv
    # 3 versions of diffs is for convenience during analysis in R
    outs:
      - data/mining/240522-split/freq/motif_profile.csv
      - data/mining/240522-split/freq/diffs_train.csv
      - data/mining/240522-split/freq/diffs_all.csv
      - data/mining/240522-split/freq/diffs_valid.csv




