stages:
  setup:
    cmd: src/setup.sh
  clean:
    cmd: src/clean_expression.py data/zhong2021/s4-plasma_protein_profiling.csv data/zhong2021/expression.csv --meta_out data/zhong2021/meta.csv
    deps:
      - src/clean_expression.py
    outs:
      - data/zhong2021/expression.csv
      - data/zhong2021/meta.csv
  bin_expression:
    cmd: >
      src/motif_mining/graphs/bin_expression.py 
      data/zhong2021/expression.csv 
      data/mining 
      --value npx 
      --node_id symbol
    deps:
      - src/motif_mining/graphs/bin_expression.py
      - data/zhong2021/expression.csv
    outs: 
      - data/mining/expression/expression_binned.csv
      - data/mining/expression/breaks.txt
  generate_graphs:
    cmd: >
      src/motif_mining/graphs/generate.py 
      data/mining/expression/expression_binned.csv 
      data/string/9606.protein.physical.links.detailed.v12.0.txt.gz
      data/mining/graphs 
      --node_ids data/string/string_v12_idmap.csv
      --var_id symbol
      --obs_id id_visit
      --clobber
    deps:
      - src/motif_mining/graphs/generate.py
      - data/mining/expression/expression_binned.csv
      - data/string/string_v12_idmap.csv

  ## Split data exp
  setup_exp:
    cmd: >
      src/motif_mining/mining/setup_experiment.py
      data/zhong2021/meta.csv
      data/mining/graphs
      data/mining/240522-split
      --p_train 0.8
      --subject_id subject_id
      --obs_id id_visit
      --group_id visit
  
  # mine/extract on training set only
  mine:
    cmd: >
      src/motif_mining/mining/gaston_cov.py
      data/mining/240522-split/train
      --size 3
      --support 30
  extract:
    cmd: >
      src/motif_mining/mining/extract_results.py
      data/mining/240522-split/train
      --purge_motifs
      --processes 8
      
