stages:
  setup:
    cmd: src/setup.sh
  clean:
    cmd: >
      src/clean_expression.py
      data/zhong2021/s4-plasma_protein_profiling.csv
      data/zhong2021/expression.csv
      --meta_out data/zhong2021/meta.csv
    deps:
      - src/clean_expression.py
      - data/zhong2021/s4-plasma_protein_profiling.csv
    outs:
      - data/zhong2021/expression.csv
      - data/zhong2021/meta.csv
  bin_expression:
    cmd: >
      src/motif_mining/graphs/bin_expression.py 
      data/zhong2021/expression.csv 
      data/mining 
      --value npx 
      --var_id symbol
      --idmap data/string/string_v12_idmap.csv
    deps:
      - src/motif_mining/graphs/bin_expression.py
      - data/zhong2021/expression.csv
    outs: 
      - data/mining/expression/expression_binned.csv
  generate_graphs:
    cmd: >
      src/motif_mining/graphs/generate.py 
      data/mining/expression/expression_binned.csv 
      data/string/9606.protein.physical.links.detailed.v12.0.txt.gz
      data/mining/graphs 
      --clobber
    deps:
      - src/motif_mining/graphs/generate.py
      - data/mining/expression/expression_binned.csv
      - data/string/string_v12_idmap.csv

  ## Split data exp
  setup_exp:
    cmd: >
      src/motif_mining/mining/setup_experiment.py
      data/zhong2021/meta.csv
      data/mining/graphs
      data/mining/240522-split
      --p_train 0.8
      --subject_id subject_id
      --obs_id obs_id
      --group_id visit
  
  # mine/extract on training set only
  mine:
    cmd: >
      src/motif_mining/mining/gaston_cov.py
      data/mining/240522-split/train
      --size 3
      --support 30
  join_metadata:
    cmd: >
      src/motif_mining/mining/join_metadata.py
      data/zhong2021/meta.csv
      data/mining/240522-split/train/gaston_files
      data/mining/240522-split/train/meta.csv
    outs:
      - data/mining/240522-split/train/meta.csv
  extract:
    cmd: >
      src/motif_mining/mining/extract_results.py
      data/mining/240522-split/train
      --purge_motifs
      --processes 8
    outs:
      - data/mining/240522-split/train/motifs
  match:
    cmd: >
      src/motif_mining/mining/match_motifs.py
      data/mining/240522-split/train/motifs
      data/mining/240522-split/train/meta.csv
      data/zhong2021/meta.csv
      data/mining/240522-split/freq/matched_motifs.csv
      -e data/mining/expression/expression_binned.csv
    outs:
      - data/mining/240522-split/freq/matched_motifs.csv
  # analysis/results >> Rmd
  analysis:
    cmd: echo 'placeholder'
    deps:
      - data/mining/240522-split/freq/matched_motifs.csv
      - data/zhong2021/expression.csv
      - data/zhong2021/meta.csv
      - data/zhong2021/s4-plasma_protein_profiling.csv
      - data/zhong2021/s6-diff_proteins.csv




